python max.py AAL
#python max.py AAPL
python max.py ADBE
python max.py ADI
python max.py ADP
python max.py ADSK
python max.py ALGN
python max.py ALXN
python max.py AMAT
python max.py AMGN
#python max.py AMZN
python max.py ASML
python max.py ATVI
python max.py AVGO
#python max.py BIDU
python max.py BIIB
python max.py BKNG
python max.py BMRN
python max.py CA
python max.py CDNS
python max.py CELG
python max.py CERN
python max.py CHKP
python max.py CHTR
python max.py CMCSA
python max.py COST
python max.py CSCO
python max.py CSX
python max.py CTAS
python max.py CTRP
python max.py CTSH
python max.py CTXS
python max.py DISH
python max.py DLTR
python max.py EA
python max.py EBAY
python max.py ESRX
python max.py EXPE
python max.py FAST
#python max.py FB
python max.py FISV
python max.py FOX
python max.py FOXA
python max.py GILD
#python max.py GOOG
python max.py GOOGL
python max.py HAS
python max.py HOLX
python max.py HSIC
python max.py IDXX
python max.py ILMN
python max.py INCY
python max.py INTC
python max.py INTU
python max.py ISRG
python max.py JBHT
python max.py JD
python max.py KHC
python max.py KLAC
python max.py LBTYA
python max.py LBTYK
python max.py LRCX
python max.py LVNTA
python max.py MAR
python max.py MCHP
python max.py MDLZ
python max.py MELI
python max.py MNST
python max.py MSFT
python max.py MU
python max.py MXIM
python max.py MYL
python max.py NFLX
python max.py NTES
python max.py NVDA
python max.py ORLY
python max.py PAYX
python max.py PCAR
python max.py PYPL
python max.py QCOM
python max.py QVCA
python max.py REGN
python max.py ROST
python max.py SBUX
python max.py SHPG
python max.py SIRI
python max.py SNPS
python max.py STX
python max.py SWKS
python max.py SYMC
python max.py TMUS
python max.py TSLA
python max.py TTWO
python max.py TXN
python max.py ULTA
python max.py VOD
python max.py VRSK
python max.py VRTX
python max.py WBA
python max.py WDAY
python max.py WDC
python max.py WYNN
python max.py XLNX
python max.py XRAY
